theme = "kiera"
title = "somtochiama"
languageCode = "en-us"
baseURL = "https://somtochiama.github.io/"
copyright = "© 2020"

summaryLength = 0
enableEmoji = true
pygmentsCodeFences = true

[params.author]
  name = "Somtochi Onyekwere"
  email = "somtochionyekwere@gmail.com"
  twitter = "somtochiama"
  github = "somtochiama"
  linkedin = "somtochi-onyekwere"

# Optional params
[params]
  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"
  name = "Somtochi Onyekwere"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true
  tagline = "tending my little internet garden"
  customCSS = []  #Optional Customised CSS
  disableDarkModeCSS = false # disables css style for users using dark-mode


  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 30

# allows raw html in Markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Add your Disqus shortname here.
disqusShortname = "somtochi-blog"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = ""
